name: Docker Build Test

on:
  push:
    branches: [ "main" ]  # When pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . --file Dockerfile -t my-wp-site:test